#!/bin/bash

rm openbar_search/migrations/*
rm openbar_users/migrations/*
rm db.sqlite3

python manage.py makemigrations
python manage.py migrate

python manage.py loaddata data/topics.json
python manage.py loaddata data/subset_querydata_1000.json
python manage.py loaddata data/subset_querydata_2000.json
python manage.py loaddata data/subset_querydata_3000.json
python manage.py loaddata data/subset_querydata_4000.json
python manage.py loaddata data/subset_querydata_5000.json
python manage.py loaddata data/subset_querydata_6000.json
python manage.py loaddata data/subset_querydata_7000.json
python manage.py loaddata data/subset_querydata_8000.json
python manage.py loaddata data/subset_querydata_9000.json
python manage.py loaddata data/subset_querydata_10000.json
python manage.py loaddata data/subset_querydata_11000.json
